defmodule Demo.Cities do
def suggest(""), do: []

  def suggest(prefix) do
    Enum.filter(list_cities(), &has_prefix?(&1, prefix))
  end

  defp has_prefix?(city, prefix) do
    String.starts_with?(String.downcase(city), String.downcase(prefix))
  end

  def list_cities do
    [
      # Naomi's creation
      "Quimser, MB",
      "Yorkston, MB",
      "Abilene, TX",
      "Addison, IL",
      "Akron, OH",
      "Alameda, CA",
      "Albany, OR",
      "Albany, NY",
      "Albany, GA",
      "Albuquerque, NM",
      "Alexandria, LA",
      "Alexandria, VA",
      "Alhambra, CA",
      "Aliso Viejo, CA",
      "Allen, TX",
      "Allentown, PA",
      "Alpharetta, GA",
      "Altamonte Springs, FL",
      "Altoona, PA",
      "Amarillo, TX",
      "Ames, IA",
      "Anaheim, CA",
      "Anchorage, AK",
      "Anderson, IN",
      "Ankeny, IA",
      "Ann Arbor, MI",
      "Annapolis, MD",
      "Antioch, CA",
      "Apache Junction, AZ",
      "Apex, NC",
      "Apopka, FL",
      "Apple Valley, MN",
      "Apple Valley, CA",
      "Appleton, WI",
      "Arcadia, CA",
      "Arlington, TX",
      "Arlington Heights, IL",
      "Arvada, CO",
      "Asheville, NC",
      "Athens-Clarke County, GA",
      "Atlanta, GA",
      "Atlantic City, NJ",
      "Attleboro, MA",
      "Auburn, AL",
      "Auburn, WA",
      "Augusta-Richmond County, GA",
      "Aurora, CO",
      "Aurora, IL",
      "Austin, TX",
      "Aventura, FL",
      "Avondale, AZ",
      "Azusa, CA",
      "Bakersfield, CA",
      "Baldwin Park, CA",
      "Baltimore, MD",
      "Barnstable Town, MA",
      "Bartlett, IL",
      "Bartlett, TN",
      "Baton Rouge, LA",
      "Battle Creek, MI",
      "Bayonne, NJ",
      "Baytown, TX",
      "Beaumont, CA",
      "Beaumont, TX",
      "Beavercreek, OH",
      "Beaverton, OR",
      "Bedford, TX",
      "Bell Gardens, CA",
      "Belleville, IL",
      "Bellevue, WA",
      "Bellevue, NE",
      "Bellflower, CA",
      "Bellingham, WA",
      "Beloit, WI",
      "Bend, OR",
      "Bentonville, AR",
      "Berkeley, CA",
      "Berwyn, IL",
      "Bethlehem, PA",
      "Beverly, MA",
      "Billings, MT",
      "Biloxi, MS",
      "Binghamton, NY",
      "Birmingham, AL",
      "Bismarck, ND",
      "Blacksburg, VA",
      "Blaine, MN",
      "Bloomington, IN",
      "Bloomington, MN",
      "Bloomington, IL",
      "Blue Springs, MO",
      "Boca Raton, FL",
      "Boise City, ID",
      "Bolingbrook, IL",
      "Bonita Springs, FL",
      "Bossier City, LA",
      "Boston, MA",
      "Boulder, CO",
      "Bountiful, UT",
      "Bowie, MD",
      "Bowling Green, KY",
      "Boynton Beach, FL",
      "Bozeman, MT",
      "Bradenton, FL",
      "Brea, CA",
      "Bremerton, WA",
      "Brentwood, CA",
      "Brentwood, TN",
      "Bridgeport, CT",
      "Bristol, CT",
      "Brockton, MA",
      "Broken Arrow, OK",
      "Brookfield, WI",
      "Brookhaven, GA",
      "Brooklyn Park, MN",
      "Broomfield, CO",
      "Brownsville, TX",
      "Bryan, TX",
      "Buckeye, AZ",
      "Buena Park, CA",
      "Buffalo, NY",
      "Buffalo Grove, IL",
      "Bullhead City, AZ",
      "Burbank, CA",
      "Burien, WA",
      "Burleson, TX",
      "Burlington, NC",
      "Burlington, VT",
      "Burnsville, MN",
      "Caldwell, ID",
      "Calexico, CA",
      "Calumet City, IL",
      "Camarillo, CA",
      "Cambridge, MA",
      "Camden, NJ",
      "Campbell, CA",
      "Canton, OH",
      "Cape Coral, FL",
      "Cape Girardeau, MO",
      "Carlsbad, CA",
      "Carmel, IN",
      "Carol Stream, IL",
      "Carpentersville, IL",
    ]
  end
end
